"""'first_migration_table'

Revision ID: 97d07fb06732
Revises: 981ba0df0901
Create Date: 2019-12-15 23:25:30.359080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d07fb06732'
down_revision = '981ba0df0901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('receive_by', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('receiver', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=5000), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receive_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sent_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
